### ISSUE TITLE
some breaking changes in eeguana

### ISSUE THREAD

**Issue by bnicenboim** [jaromilfrossard/permuco#7]
Just a heads up that I changed some of the arguments names and order. If you get an error now from eeguana, it's probably, because the new argument name has a ".".
Feel free to close, if you can build your package again without problems.

**Comment by jaromilfrossard** [comment]
thanks! However permuco does not depends on eeguana, only permuco4brain.

I will make the necessary changes in the vignette of permuco4brain  as soon as possible.
